server:
  name: "cab-data-researcher-app"
  idletimeout: 5s
  readtimeout: 5s
  writetimeout: 5s
  addr: ":8080"

db:
  driver: postgres
  datasource: "user=postgres dbname=ny_cab_data sslmode=verify-full"
